[NFC][Sepolicy]: Fix the AVC denial issue
error: avc:  denied  { search } for  comm="com.android.nfc" name="nfc" dev="dm-56" ino=865 scontext=u:r:nfc:s0 tcontext=u:object_r:vendor_nfc_vendor_data_file:s0 tclass=dir permissive=0

Change-Id: Icb0b3ca1ab3bb6f669f48457571bebf5cfcbd03c
(cherry picked from commit d73c2477e1cda5082d2079a10d158884e39f48fd)